Flownative:
  Aws:
    S3:
      profiles:
        # Default credentials and client options - override these in your settings with real values
        # For more documentation regarding options, see http://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html#client-configuration-options
        default:

          # Access Control List. Override in your own Settings.yaml with '' to not provide public read access to an object in S3
          # To access these objects use SignedCookie or SignedURL method in combination with AWS CloudFront
          acl: 'public-read'

          # Select the API version to use
          version: '2006-03-01'

          # Don't use the old signature v2 - certain regions don't support them
          signature_version: 'v4'

          # Define credentials for authentication
          #credentials:
            #key: 'ABCD123EFG456HIJ7890'
            #secret: 'aBc123DEf456GHi789JKlMNopqRsTuVWXyz12345'

          # If the region is not specified, the default region will be used (according to the S3 service)
          #region: 'us-west-1'

          # URI Scheme of the base URL (e.g.. 'https', 'http') used when endpoint is not supplied
          scheme: 'https'

          # Custom endpoint, for example for Google Cloud Storage
          #endpoint: 'https://storage.googleapis.com/<bucket>'
